import {test,expect} from '@playwright/test';import {mkdirSync,writeFileSync} from 'node:fs';
import {site,viewer,push,db,png,pdf,login,gateway} from '../helpers.ts';import {hash} from '../../server/core.ts';import {scopeInbox} from './scope.ts';
test('V3 polish, keyboard, preferences, paste and incremental cards on deployed preview',async({browser})=>{
 test.setTimeout(240000);const results:Record<string,unknown>={};const owned:string[]=[],files:string[]=[];
 const context=await browser.newContext({permissions:['clipboard-read','clipboard-write'],viewport:{width:1440,height:1050}});await scopeInbox(context,owned,files);const page=await context.newPage();const errors:string[]=[];page.on('pageerror',e=>errors.push(e.name));
 try{
  await page.goto(site+'/#access='+viewer);await expect(page.locator('#unlock')).toBeEnabled({timeout:20000});await page.locator('#code').fill('000');await page.locator('#unlock').click();await expect(page.locator('#workspace')).toBeVisible({timeout:25000});
  const exact='Pt: SYNTHETIC example — no patient\r\nDx: Workflow test only\r\n\r\n  Whitespace preserved.\tEnd.\n';
  for(const text of [exact,'Short note','Long synthetic note\n'+('A readable line for testing.\n'.repeat(14))]){const r=await push(text);expect(r.status).toBe(200);owned.push(r.data.id);}
  await expect(page.locator('.note-card')).toHaveCount(3,{timeout:22000});await expect(page.locator('.note-patient')).toHaveText('Pt: SYNTHETIC example — no patient');expect(await page.locator('.note-text').first().textContent()).toBe(exact);results.patient_preview_and_exact_whitespace=true;
  const heights=await page.locator('.note-card').evaluateAll(cards=>cards.map(c=>c.getBoundingClientRect().height));expect(heights[1]).toBeLessThan(200);expect(heights[2]).toBeGreaterThan(400);results.content_sized_cards=true;
  await expect(page.locator('.expiry-info').first()).toContainText('Expires ');await expect(page.locator('.expiry').first()).toContainText('left');results.absolute_expiry=true;
  await expect(page.locator('#copy-next')).toHaveText('Copy next · 3 remaining');await expect(page.locator('#clear-copied')).toBeDisabled();
  await page.evaluate(()=>{(window as any).firstCard=document.querySelector('.note-card');(window as any).copiedText='';navigator.clipboard.writeText=async text=>{(window as any).copiedText=text;};});
  await page.locator('#copy-next').click();await expect(page.locator('#copy-next')).toHaveText('Copy next · 2 remaining');expect(await page.evaluate(()=>(window as any).copiedText)).toBe(exact);expect(await page.evaluate(()=>(window as any).firstCard===document.querySelector('.note-card'))).toBe(true);expect(await page.locator('.note-card').nth(1).evaluate(el=>el===document.activeElement)).toBe(true);results.copy_next_count_focus_incremental_dom=true;
  await page.keyboard.press('c');await expect(page.locator('#copy-next')).toHaveText('Copy next · 1 remaining');await page.keyboard.press('k');expect(await page.locator('.note-card').nth(1).evaluate(el=>el===document.activeElement)).toBe(true);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await expect(page.locator('#copy-next')).toHaveText('All notes copied ✓');await expect(page.locator('#copy-next')).toBeDisabled();results.keyboard_copy_navigation=true;
  await page.locator('#clear-copied').click();await expect(page.locator('#confirm-title')).toHaveText('Clear 3 copied notes?');await page.keyboard.press('Escape');await expect(page.locator('#confirmation')).not.toBeVisible();results.clear_copied_exact_count=true;
  await page.locator('#view').selectOption('compact');await expect(page.locator('.note-text:visible')).toHaveCount(0);await page.locator('.expand').first().click();await expect(page.locator('.note-text:visible')).toHaveCount(1);await page.locator('.expand').first().click();await page.locator('.note-label').nth(1).click();await expect(page.locator('.note-text').nth(1)).toBeVisible();results.compact_expand=true;
  await page.locator('#theme').selectOption('dark');await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.reload();await expect(page.locator('#workspace')).toBeVisible({timeout:20000});await expect(page.locator('#view')).toHaveValue('compact');await expect(page.locator('#theme')).toHaveValue('dark');await expect(page.locator('.note-copy')).toHaveText(['Copied ✓','Copied ✓','Copied ✓']);results.preference_and_copied_persistence=true;
  await page.emulateMedia({colorScheme:'light'});await page.locator('#theme').selectOption('system');await expect(page.locator('html')).toHaveAttribute('data-theme','light');await page.emulateMedia({colorScheme:'dark'});await expect(page.locator('html')).toHaveAttribute('data-theme','dark');results.system_theme=true;
  await page.locator('#file-input').setInputFiles([{name:'preview.png',mimeType:'image/png',buffer:png},{name:'preview.pdf',mimeType:'application/pdf',buffer:pdf()}]);await expect(page.locator('.file')).toHaveCount(2,{timeout:35000});await expect(page.locator('.file-meta').first()).toContainText('Workstation');await expect(page.locator('.file-meta').first()).toContainText('Received');await expect(page.locator('.file-meta').first()).toContainText('Expires');results.file_metadata=true;
  await page.getByRole('button',{name:'Preview preview.png',exact:true}).click();await expect(page.locator('#file-preview img')).toBeVisible();await expect.poll(()=>page.locator('#file-preview img').evaluate((img:HTMLImageElement)=>img.naturalWidth)).toBeGreaterThan(0);await page.keyboard.press('Escape');await expect(page.locator('#preview-content')).toBeEmpty();
  await page.getByRole('button',{name:'Preview preview.pdf',exact:true}).click();if(await page.evaluate(()=>navigator.pdfViewerEnabled)){await expect(page.locator('#file-preview iframe')).toBeVisible();results.pdf_native_preview=true;}else{await expect(page.getByRole('button',{name:'Open in browser',exact:true})).toBeVisible();results.pdf_unsupported_fallback=true;}await page.locator('#preview-close').click();results.image_pdf_modal_escape=true;
  await page.evaluate(async bytes=>{await navigator.clipboard.write([new ClipboardItem({'image/png':new Blob([new Uint8Array(bytes)],{type:'image/png'})})]);},Array.from(png));await page.locator('.note-card').first().focus();await page.keyboard.press('Control+V');await expect(page.locator('.file')).toHaveCount(3,{timeout:25000});await expect(page.locator('.file-name').last()).toHaveText(/^Screenshot-.*\.png$/);results.real_clipboard_image_paste=true;
  await page.evaluate(()=>{const input=document.createElement('textarea');input.id='test-typing';document.body.append(input);input.focus();});await page.keyboard.type('cjk');expect(await page.locator('#test-typing').inputValue()).toBe('cjk');await page.keyboard.press('Control+V');await expect(page.locator('#queue .queue-name').filter({hasText:'Pasted image'})).toHaveCount(0,{timeout:6000});await page.locator('#test-typing').evaluate(el=>el.remove());results.paste_and_shortcuts_ignore_fields=true;
  for(let i=4;i<=20;i++){const r=await push(`Pt: Synthetic example ${i}\nDx: Workflow verification\n\nTest note ${i}.`);owned.push(r.data.id);}
  await expect(page.locator('.note-card')).toHaveCount(20,{timeout:20000});const started=Date.now();await page.locator('#sort').selectOption('newest');await expect(page.locator('.note-text').first()).toHaveText('Pt: Synthetic example 20\nDx: Workflow verification\n\nTest note 20.');results.twenty_notes_order_ms=Date.now()-started;
  await page.locator('.note-card').first().getByRole('button',{name:'Delete Note 01',exact:true}).click();await expect(page.locator('#confirm-title')).toHaveText('Delete Note 01?');await page.keyboard.press('Escape');results.delete_number_follows_sort=true;
  await page.locator('#sort').selectOption('oldest');await page.locator('#theme').selectOption('light');await page.locator('#view').selectOption('comfortable');mkdirSync('artifacts',{recursive:true});await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/v3-polish-light.png',animations:'disabled'});
  await page.locator('#view').selectOption('compact');await page.locator('#theme').selectOption('dark');await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/v3-polish-dark-compact.png',animations:'disabled'});await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:'artifacts/v3-polish-mobile.png',animations:'disabled'});results.responsive=true;
  const keys=await page.evaluate(()=>Object.keys(localStorage).sort());expect(keys).toEqual(['relay-v3-copied','relay-v3-theme','relay-v3-view']);expect(await page.evaluate(()=>Object.keys(sessionStorage))).toEqual([]);results.preference_ids_only_storage=true;
  const old=(await context.cookies()).find(c=>c.name==='__Host-relay_v3')!.value;await page.locator('#lock').click();await expect(page.locator('#notes')).toBeEmpty();await expect(page.locator('#files')).toBeEmpty();await expect(page.locator('#unlock')).toBeEnabled({timeout:10000});expect((await gateway('/state',old)).status).toBe(401);const replacement=(await context.cookies()).find(c=>c.name==='__Host-relay_v3')!.value;expect(replacement).not.toBe(old);await page.locator('#code').fill('000');await page.locator('#unlock').click();await expect(page.locator('#workspace')).toBeVisible({timeout:20000});results.lock_immediate_hide_rotates_session=true;
  expect(errors).toEqual([]);results.no_browser_errors=true;writeFileSync('tests/polish-browser-results.json',JSON.stringify({at:new Date().toISOString(),results},null,2)+'\n');
 }finally{const token=await login('polish-cleanup');await gateway('/delete-notes',token,{ids:owned});await gateway('/delete-files',token,{ids:files});await db('relay_v3_sessions?hash=eq.'+await hash(token),'DELETE');const cookie=(await context.cookies()).find(c=>c.name==='__Host-relay_v3');if(cookie)await db('relay_v3_sessions?hash=eq.'+await hash(cookie.value),'DELETE');await context.close();}
});
