import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {site,edge,root,viewer,encryption,signing,db,storage,push,gateway,login,upload,png,pdf} from '../tests/helpers.ts';
import {makeEnvelope,randomToken,hash,b64,hmac,signedData} from '../server/core.ts';
const results:{name:string;ms:number}[]=[];
async function check(name:string,fn:()=>Promise<void>){const at=Date.now();await fn();results.push({name,ms:Date.now()-at});console.log('PASS '+name);}
let token='';const owned:string[]=[],files:string[]=[];
try{
 await check('viewer secret required; PIN alone cannot enter',async()=>{assert.equal((await gateway('/exchange','',{access:randomToken()})).status,401);assert.equal((await gateway('/login','',{pin:'000'})).status,401);assert.equal((await fetch(edge+'/state')).status,401);});
 await check('viewer secret exchange and PIN 000 login',async()=>{token=await login();assert.equal((await gateway('/state',token)).status,200);});
 await check('first append, multiple append and ordering',async()=>{for(const name of ['Test Note A','Test Note B','Test Note C']){const r=await push(name);assert.equal(r.status,200);owned.push(r.data.id);}const s=await(await gateway('/state',token)).json();assert.deepEqual(s.notes.filter((n:{id:string})=>owned.includes(n.id)).map((n:{text:string})=>n.text),['Test Note A','Test Note B','Test Note C']);});
 await check('independent 12-hour TTL for each note',async()=>{const rows=await db('relay_v3_notes?id=in.('+owned.join(',')+')&order=sequence.asc');for(const r of rows)assert.equal(Date.parse(r.expires_at)-Date.parse(r.received_at),43200000);assert.ok(Date.parse(rows[2].expires_at)>Date.parse(rows[0].expires_at));});
 await check('encrypted GET appends without plaintext URL',async()=>{const r=await push('Encrypted GET synthetic note',true);assert.equal(r.status,200);owned.push(r.data.id);});
 await check('replay rejection acknowledges same delivery without duplicate',async()=>{const e=await makeEnvelope('Replay synthetic',encryption,signing);const a=await push('',false,e);assert.equal(a.status,200);owned.push(a.data.id);const b=await push('',false,e);assert.equal(b.status,409);assert.equal(b.data.error,'replayed');assert.equal(b.data.accepted_id,a.data.id);});
 await check('duplicate version and stale version rejected',async()=>{const rows=await db('relay_v3_state?id=eq.1');const e=await makeEnvelope('Duplicate synthetic',encryption,signing,Number(rows[0].version));const r=await push('',false,e);assert.equal(r.status,409);assert.equal(r.data.error,'duplicate_or_stale_version');});
 await check('nonce reuse rejected even with new valid version',async()=>{const e=await makeEnvelope('Nonce synthetic',encryption,signing);const a=await push('',false,e);assert.equal(a.status,200);owned.push(a.data.id);const other=await makeEnvelope('New synthetic',encryption,signing);const {encryptText,associatedData}=await import('../server/core.ts');other.nonce=e.nonce;Object.assign(other,await encryptText('New synthetic',encryption,associatedData(other)));other.signature=await hmac(signing,signedData(other));const b=await push('',false,other);assert.equal(b.status,409);assert.equal(b.data.error,'nonce_reused');});
 await check('invalid signature',async()=>{const e=await makeEnvelope('Signature synthetic',encryption,signing);e.signature=randomToken();assert.equal((await push('',false,e)).status,401);});
 await check('invalid ciphertext with valid HMAC',async()=>{const e=await makeEnvelope('Cipher synthetic',encryption,signing);e.ciphertext=b64(new Uint8Array(20));e.signature=await hmac(signing,signedData(e));assert.equal((await push('',false,e)).status,400);});
 await check('stale timestamp rejected',async()=>{const e=await makeEnvelope('Old synthetic',encryption,signing,Date.now(),Date.now()-121000);assert.equal((await push('',false,e)).status,401);});
 await check('wrong PIN throttles across attempts',async()=>{const r=await gateway('/exchange','',{access:viewer},'pin-throttle-test');const t=(await r.json()).session;for(let i=0;i<5;i++)assert.equal((await gateway('/login',t,{pin:'111'},'pin-throttle-test')).status,401);assert.equal((await gateway('/login',t,{pin:'000'},'pin-throttle-test')).status,429);await db('relay_v3_sessions?hash=eq.'+await hash(t),'DELETE');});
 await check('expired session rejected by server',async()=>{const t=await login('session-expiry-test');await db('relay_v3_sessions?hash=eq.'+await hash(t),'PATCH',{expires_at:new Date(Date.now()-1000).toISOString()});assert.equal((await gateway('/state',t)).status,401);});
 await check('file upload and encrypted private storage',async()=>{const r=await upload(token,png,'synthetic.png','image/png');assert.equal(r.status,200);files.push(r.data.id);const object=await storage(`object/relay-v3-private/${r.data.id}/data`);const ciphertext=new Uint8Array(await object.arrayBuffer());assert.notDeepEqual(ciphertext,new Uint8Array(png));assert.equal((await fetch(root+`/storage/v1/object/public/relay-v3-private/${r.data.id}/data`)).ok,false);});
 await check('PDF upload and exact signed download',async()=>{const bytes=pdf();const r=await upload(token,bytes,'synthetic.pdf','application/pdf');assert.equal(r.status,200);files.push(r.data.id);const link=await(await gateway('/file-url',token,{id:r.data.id,mode:'download'})).json();const file=await fetch(link.url);assert.equal(file.status,200);assert.deepEqual(Buffer.from(await file.arrayBuffer()),bytes);assert.match(file.headers.get('cache-control')||'',/no-store/);});
 await check('byte validation rejects filename and MIME spoof',async()=>{assert.equal((await upload(token,Buffer.from('<html>not an image</html>'),'fake.png','image/png')).status,415);});
 await check('20 MB file accepted; larger file rejected server-side',async()=>{const ok=await upload(token,pdf(20*1024*1024),'limit.pdf','application/pdf');assert.equal(ok.status,200);files.push(ok.data.id);const bad=await upload(token,pdf(20*1024*1024+1),'too-large.pdf','application/pdf');assert.equal(bad.status,413);});
 await check('expired signed URL rejected and cannot outlive file TTL',async()=>{const id=files[0],exp=Date.now()-1000,mode='download',signature=await hmac(process.env.RELAY_V3_LINK_SECRET!,`file-v3.${id}.${exp}.${mode}`);assert.equal((await fetch(`${edge}/file/${id}?expires=${exp}&mode=${mode}&signature=${signature}`)).status,401);await db('relay_v3_objects?id=eq.'+id,'PATCH',{expires_at:new Date(Date.now()+20000).toISOString()});const link=await(await gateway('/file-url',token,{id,mode})).json();assert.ok(link.expires_at<=Date.now()+20000);});
 await check('expiry filtering hides only expired note',async()=>{await db('relay_v3_notes?id=eq.'+owned[0],'PATCH',{expires_at:new Date(Date.now()-1000).toISOString()});await db('relay_v3_objects?id=eq.'+owned[0],'PATCH',{expires_at:new Date(Date.now()-1000).toISOString()});const s=await(await gateway('/state',token)).json();assert.equal(s.notes.some((n:{id:string})=>n.id===owned[0]),false);assert.equal(s.notes.some((n:{id:string})=>n.id===owned[1]),true);});
 await check('unattended scheduled physical note/file cleanup',async()=>{const note=owned[0],file=files[0];await db('relay_v3_objects?id=eq.'+file,'PATCH',{expires_at:new Date(Date.now()-1000).toISOString()});const start=Date.now();while(Date.now()-start<110000){const rows=await db(`relay_v3_objects?id=in.(${note},${file})`);if(!rows.length){assert.equal((await storage(`object/relay-v3-private/${note}/data`)).ok,false);assert.equal((await storage(`object/relay-v3-private/${file}/data`)).ok,false);return;}await new Promise(r=>setTimeout(r,4000));}throw new Error('Scheduled cleanup timed out');});
 await check('clear selected snapshots keeps a newer arrival',async()=>{const r=await push('Arrival during clear confirmation');assert.equal(r.status,200);owned.push(r.data.id);assert.equal((await gateway('/delete-notes',token,{ids:owned.slice(0,-1)})).status,200);const s=await(await gateway('/state',token)).json();assert.ok(s.notes.some((n:{id:string})=>n.id===r.data.id));});
 await check('lock revokes access until PIN is entered again',async()=>{assert.equal((await gateway('/lock',token,{})).status,200);assert.equal((await gateway('/state',token)).status,401);assert.equal((await gateway('/login',token,{pin:'000'})).status,200);});
 writeFileSync('tests/live-results.json',JSON.stringify({at:new Date().toISOString(),passed:results.length,results},null,2)+'\n');
}finally{
 if(token){await gateway('/delete-notes',token,{ids:owned});await gateway('/delete-files',token,{ids:files});await db('relay_v3_sessions?hash=eq.'+await hash(token),'DELETE');}
}
