import assert from 'node:assert/strict';import {writeFileSync} from 'node:fs';
import {site,db,gateway,login} from '../tests/helpers.ts';import {hash,randomToken} from '../server/core.ts';
const results:string[]=[],owned:string[]=[];let token='',access='',refresh='',client='',grant='';
async function check(name:string,fn:()=>Promise<void>){await fn();results.push(name);console.log('PASS '+name);}
const post=(path:string,body:unknown,headers:Record<string,string>={})=>fetch(site+path,{method:'POST',headers:{'content-type':'application/json',...headers},body:JSON.stringify(body)});
const exchange=(body:Record<string,string>)=>fetch(site+'/oauth/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body)});
let session='';
async function rpc(id:number,method:string,params:unknown={}){const r=await post('/mcp',{jsonrpc:'2.0',id,method,params},{authorization:'Bearer '+access,'mcp-session-id':session});const data=await r.json();assert.equal(r.status,200);return {r,data};}
try{
 const before=await db('relay_v3_notes?select=id,expires_at');
 await check('OAuth discovery and unauthenticated MCP denial',async()=>{const r=await post('/mcp',{jsonrpc:'2.0',id:1,method:'tools/list'});assert.equal(r.status,401);assert.match(r.headers.get('www-authenticate')||'',/oauth-protected-resource/);const meta=await(await fetch(site+'/.well-known/oauth-authorization-server')).json();assert.deepEqual(meta.code_challenge_methods_supported,['S256']);});
 const verifier=randomToken(),resource=site+'/mcp',redirect='https://chatgpt.com/connector_platform_oauth_redirect';let code='';
 await check('DCR rejects other callbacks and accepts exact ChatGPT callback',async()=>{assert.equal((await post('/oauth/register',{redirect_uris:['https://example.com/callback']})).status,400);const r=await post('/oauth/register',{redirect_uris:[redirect],token_endpoint_auth_method:'none'});assert.equal(r.status,201);client=(await r.json()).client_id;});
 const auth={client_id:client,redirect_uri:redirect,resource,scope:'notes.write',state:randomToken(),response_type:'code',code_challenge:await hash(verifier),code_challenge_method:'S256'};
 await check('OAuth authorization requires unlocked private viewer',async()=>{assert.equal((await gateway('/oauth/authorize','',auth)).status,401);token=await login('sender-tests');const r=await gateway('/oauth/authorize',token,auth);assert.equal(r.status,200);const url=new URL((await r.json()).redirect);assert.equal(url.searchParams.get('iss'),site);assert.equal(url.searchParams.get('state'),auth.state);code=url.searchParams.get('code')!;});
 const body={grant_type:'authorization_code',client_id:client,redirect_uri:redirect,resource,code,code_verifier:verifier};
 await check('PKCE, audience, one-use codes and OAuth tokens',async()=>{assert.equal((await exchange({...body,code_verifier:randomToken()})).status,400);assert.equal((await exchange({...body,resource:'https://example.com'})).status,400);const r=await exchange(body);assert.equal(r.status,200);const data=await r.json();access=data.access_token;refresh=data.refresh_token;assert.equal(data.scope,'notes.write');assert.equal((await exchange(body)).status,400);grant=(await db('relay_v3_oauth_tokens?hash=eq.'+await hash(access)))[0].grant_id;});
 await check('MCP initialize and exactly one simple send_note action',async()=>{const {r,data}=await rpc(1,'initialize',{protocolVersion:'2025-06-18',capabilities:{},clientInfo:{name:'acceptance-test',version:'1'}});session=r.headers.get('mcp-session-id')!;assert.ok(session);assert.equal(data.result.protocolVersion,'2025-06-18');const list=await rpc(2,'tools/list');assert.deepEqual(list.data.result.tools.map((t:{name:string})=>t.name),['send_note']);});
 let receiptA:Record<string,unknown>;
 await check('two consecutive send_note calls append exact A and B',async()=>{const a=(await rpc(3,'tools/call',{name:'send_note',arguments:{note:'Test Note Sender A'}})).data.result;assert.equal(a.isError,false,JSON.stringify(a));receiptA=a.structuredContent;owned.push(String(receiptA.note_id));const b=(await rpc(4,'tools/call',{name:'send_note',arguments:{note:'Test Note Sender B'}})).data.result;assert.equal(b.isError,false,JSON.stringify(b));owned.push(b.structuredContent.note_id);assert.ok(b.structuredContent.version>Number(receiptA.version));const state=await(await gateway('/state',token)).json();assert.deepEqual(state.notes.filter((n:{id:string})=>owned.includes(n.id)).map((n:{text:string})=>n.text),['Test Note Sender A','Test Note Sender B']);for(const item of before.filter((n:{expires_at:string})=>Date.parse(n.expires_at)>Date.now()))assert.ok(state.notes.some((n:{id:string})=>n.id===item.id));});
 await check('same MCP request retry returns identical receipt without duplication',async()=>{const r=(await rpc(3,'tools/call',{name:'send_note',arguments:{note:'Test Note Sender A'}})).data.result;assert.deepEqual(r.structuredContent,receiptA);assert.equal((await db('relay_v3_notes?id=in.('+owned.join(',')+')')).length,2);const bad=(await rpc(3,'tools/call',{name:'send_note',arguments:{note:'Different note'}})).data.result;assert.equal(bad.isError,true);});
 await check('new intentional request with identical text appends separately',async()=>{const r=(await rpc(5,'tools/call',{name:'send_note',arguments:{note:'Test Note Sender A'}})).data.result;assert.equal(r.isError,false);assert.notEqual(r.structuredContent.note_id,receiptA.note_id);owned.push(r.structuredContent.note_id);});
 await check('OAuth refresh rotates, old refresh rejected and grant revokes',async()=>{const b={grant_type:'refresh_token',client_id:client,resource,refresh_token:refresh};const r=await exchange(b);assert.equal(r.status,200);access=(await r.json()).access_token;assert.equal((await exchange(b)).status,400);const revoke=await fetch(site+'/oauth/revoke',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:client,token:access})});assert.equal(revoke.status,200);assert.equal((await post('/mcp',{jsonrpc:'2.0',id:8,method:'tools/list'},{authorization:'Bearer '+access})).status,401);});
 writeFileSync('tests/sender-live-results.json',JSON.stringify({at:new Date().toISOString(),passed:results.length,results,chatgpt_conversation_test:false},null,2)+'\n');
}finally{
 if(token){await gateway('/delete-notes',token,{ids:owned});await db('relay_v3_sessions?hash=eq.'+await hash(token),'DELETE');}
 if(grant){await db('relay_v3_oauth_tokens?grant_id=eq.'+grant,'DELETE');await db('relay_v3_sender_jobs?grant_id=eq.'+grant,'DELETE');}
 if(client)await db('relay_v3_oauth_clients?id=eq.'+client,'DELETE');
}
