import test from 'node:test';
import assert from 'node:assert/strict';
import { randomToken, makeEnvelope, verifyEnvelope, decryptText, associatedData, hmac, signedData, issueSession, verifySession, sniffFile, MAX_FILE, readLimited, RelayError } from '../server/core.ts';
import { copyThenClear } from '../src/clipboard.ts';
import { connectionStatus,pollingDelay } from '../src/connection.ts';
import { settings } from '../server/config.ts';
const encryption=randomToken(), signing=randomToken(), now=Date.now();
const text='SYNTHETIC RELAY TEST ONLY\r\n\r\n  Spacing preserved\t✓\nملاحظة اختبار\n';
test('valid encrypted note round-trips exact whitespace and Unicode',async()=>{const e=await makeEnvelope(text,encryption,signing,now,now);await verifyEnvelope(e,encryption,signing,now);assert.equal(await decryptText(e,encryption,associatedData(e)),text);assert.ok(!JSON.stringify(e).includes('SYNTHETIC'));});
test('invalid signature is rejected',async()=>{const e=await makeEnvelope(text,encryption,signing,now,now);e.signature=randomToken();await assert.rejects(()=>verifyEnvelope(e,encryption,signing,now),{status:401});});
test('signed but wrongly encrypted payload is rejected',async()=>{const e=await makeEnvelope(text,randomToken(),signing,now,now);await assert.rejects(()=>verifyEnvelope(e,encryption,signing,now),{code:'invalid_envelope'});});
test('modified AES tag rejected even with fresh valid HMAC',async()=>{const e=await makeEnvelope(text,encryption,signing,now,now);e.ciphertext=e.ciphertext.slice(0,-4)+'AAAA';e.signature=await hmac(signing,signedData(e));await assert.rejects(()=>verifyEnvelope(e,encryption,signing,now));});
test('expired request and future request rejected',async()=>{for(const timestamp of [now-121000,now+121000]){const e=await makeEnvelope(text,encryption,signing,now,timestamp);await assert.rejects(()=>verifyEnvelope(e,encryption,signing,now),{code:'expired_request'});}});
test('unsafe and non-integer versions rejected',async()=>{for(const version of [0,1.5,Number.MAX_SAFE_INTEGER+1]){const e=await makeEnvelope(text,encryption,signing,version,now);await assert.rejects(()=>verifyEnvelope(e,encryption,signing,now));}});
test('strict envelope rejects extra keys',async()=>{const e=await makeEnvelope(text,encryption,signing,now,now);await assert.rejects(()=>verifyEnvelope({...e,content:'plaintext'},encryption,signing,now),{status:400});});
test('oversized note rejected',async()=>{await assert.rejects(()=>makeEnvelope('x'.repeat(65537),encryption,signing),{status:413});});
test('session validates until exact expiration then rejects',async()=>{const secret=randomToken(),s={id:crypto.randomUUID(),device:'test',exp:now+1000};const token=await issueSession(s,secret);assert.deepEqual(await verifySession(token,secret,now),s);await assert.rejects(()=>verifySession(token,secret,now+1000),{code:'session_expired'});await assert.rejects(()=>verifySession(token,randomToken(),now));});
test('key reuse fails closed at startup',()=>{const values:Record<string,string>={};for(const key of ['SESSION','PUSH_HMAC','ENCRYPTION','GATEWAY','RATE','LINK','ADMIN','CRON'])values['RELAY_'+key+'_SECRET']=signing;assert.throws(()=>settings(k=>values[k]));});
test('file type uses bytes, not extension or MIME',()=>{assert.equal(sniffFile(new TextEncoder().encode('%PDF-1.7\nsynthetic\n%%EOF\n')),'application/pdf');assert.throws(()=>sniffFile(new TextEncoder().encode('<script>bad</script>')),{status:415});});
test('truncated PDF rejected',()=>{assert.throws(()=>sniffFile(new TextEncoder().encode('%PDF-1.7\nnot complete')),{status:415});});
test('oversized file rejected',()=>{assert.throws(()=>sniffFile(new Uint8Array(MAX_FILE+1)),{status:413});});
test('streaming size limit applies without content-length',async()=>{const request=new Request('https://test/',{method:'POST',body:'123456'});await assert.rejects(()=>readLimited(request,5),{status:413});});
test('copy failure never clears',async()=>{let clears=0;assert.equal(await copyThenClear({version:1},async()=>false,async()=>{clears++;}),false);assert.equal(clears,0);});
test('copy completes before clearing the captured version',async()=>{const order:string[]=[];let current={version:1};const snapshot=current;await copyThenClear(snapshot,async()=>{order.push('copy');current={version:2};return true;},async s=>{order.push('clear');assert.equal(s.version,1);});assert.deepEqual(order,['copy','clear']);assert.equal(current.version,2);});
test('fallback starts automatically at 4s and offline never claims Live',()=>{assert.equal(connectionStatus(true,false),'Offline');assert.equal(connectionStatus(false,true),'Fallback polling');assert.equal(pollingDelay(false,true),4000);assert.equal(connectionStatus(true,true),'Live');});
