import test from 'node:test';import assert from 'node:assert/strict';
import {metadata,preference,remainingCount,expiryLabel,type Note} from '../src/model.ts';
import {acknowledge} from '../server/sender.ts';import {sendTool} from '../server/connector.ts';
test('patient preview never fabricates metadata and keeps original whitespace',()=>{const note='Heading\r\nPt:  Synthetic  \r\nDx: Test\n';assert.deepEqual(metadata(note),{pt:'Pt:  Synthetic  ',dx:'Dx: Test'});assert.deepEqual(metadata('A short note'),{pt:'',dx:''});assert.equal(note,'Heading\r\nPt:  Synthetic  \r\nDx: Test\n');});
test('theme and compact preferences accept only supported modes',()=>{assert.equal(preference('dark',['system','light','dark'],'system'),'dark');assert.equal(preference('compact',['comfortable','compact'],'comfortable'),'compact');assert.equal(preference('bad',['system','light','dark'],'system'),'system');});
test('remaining count ignores stale copied IDs',()=>{assert.equal(remainingCount([{id:'a'},{id:'b'}] as Note[],new Set(['a','expired'])),1);});
test('expiry labels show absolute time and tomorrow',()=>{assert.match(expiryLabel('2026-09-21T12:00:00','2026-09-20T12:00:00' as unknown as number),/tomorrow/);assert.match(expiryLabel('2026-09-20T15:00:00',new Date('2026-09-20T12:00:00').getTime()),/^Expires /);});
test('sender requires successful acknowledgement, exact version and note UUID',()=>{const id='12345678-1234-4123-8123-123456789abc';assert.deepEqual(acknowledge({ok:true,id,version:12},12,200),{success:true,note_id:id,version:12});assert.equal(acknowledge({error:'replayed',accepted_id:id,version:12},12,409).note_id,id);for(const a of [{ok:false,id,version:12},{ok:true,id,version:13},{ok:true,id:'bad',version:12}])assert.throws(()=>acknowledge(a,12,200));assert.throws(()=>acknowledge({ok:true,id,version:12},12,500));});
test('MCP exposes exactly the note parameter and honestly declares a write',()=>{assert.deepEqual(sendTool.inputSchema.required,['note']);assert.equal(sendTool.inputSchema.additionalProperties,false);assert.deepEqual(Object.keys(sendTool.inputSchema.properties),['note']);assert.equal(sendTool.annotations.readOnlyHint,false);assert.equal(sendTool.annotations.destructiveHint,false);assert.equal(sendTool.securitySchemes[0].type,'oauth2');});
